#! /usr/bin/env python3
# generated by Cursor

import re
import sys
from pathlib import Path

path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).with_name("拼接.svg")
text = path.read_text(encoding="utf-8")

pattern = re.compile(
    r'(<g\s[^>]*id="stn_name_[^"]+"[^>]*transform="(?!matrix)[^"]*"[^>]*>)(.*?)(</g>)',
    re.DOTALL,
)

zh_pattern = re.compile(
    r'(<text\b(?=[^>]*font-family="SimHei)[^>]*\sdy=")-1(")',
    re.DOTALL,
)

count = 0
changed_names = []


def repl(match: re.Match[str]) -> str:
    global count
    header, body, footer = match.group(1), match.group(2), match.group(3)
    id_match = re.search(r'id="(stn_name_[^"]+)"', header)
    name = id_match.group(1) if id_match else "?"

    def zh_repl(zh_match: re.Match[str]) -> str:
        global count
        count += 1
        return zh_match.group(1) + "-2" + zh_match.group(2)

    new_body, n = zh_pattern.subn(zh_repl, body)
    if n:
        changed_names.append((name, n))
    return header + new_body + footer


new_text, groups = pattern.subn(repl, text)
print(f"groups matched: {groups}")
print(f"zh texts updated: {count}")
for name, n in changed_names:
    print(f"  {name}: {n}")

if count:
    path.write_text(new_text, encoding="utf-8")
    print("written")
else:
    print("no changes")
